contents/urls.py
from . import views
from django.urls import path

app_name = "contents"

urlpatterns = [
    path('tutorials/', views.TutorialListView.as_view(), name='tutorial-list'),
    path('scenes/', views.SceneListView.as_view(), name='scene-list'),
    path('unity/', views.UnityView.as_view(), name='unity'),
]

# <string: tutorial.__str__>/

contents/models.py
from django.db import models
from django.contrib.auth.models import User


class Section(models.Model):
    id = models.AutoField(unique=True, primary_key=True)
    name = models.CharField(max_length=120)

    def __str__(self):
        return f"{self.id}-{self.name}"


class Scene(models.Model):
    id = models.AutoField(unique=True, primary_key=True)
    name = models.CharField(max_length=120)
    description = models.CharField(max_length=120)

    def __str__(self):
        return f"{self.id}-{self.name}"


class Tutorial(Scene):
    section = models.ForeignKey(Section, on_delete=models.CASCADE)


class UserScene(Scene):
    last_modified = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

contents/views.py
from django.views.generic.list import ListView
from .models import Tutorial, Section, UserScene
from django.shortcuts import render
from django.http import HttpResponse
from django.views import View


class UnityView(View):
    template_name = 'contents/unity.html'

    def dispatch(self, request, *args, **kwargs):
        return render(request, self.template_name, *args, **kwargs)


class TutorialListView(ListView):
    model = Section
    template_name = 'contents/tutorial_list.html'
    context_object_name = 'sections'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tutorials'] = Tutorial.objects.all()
        return context


class SceneListView(ListView):
    model = UserScene
    template_name = 'contents/user_scene_list.html'
    context_object_name = 'scenes'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponse(status=401)
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        return UserScene.objects.filter(user=self.request.user)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['owner'] = self.request.user
        return context

contents/templates/contents/tutorial_list.html
{% extends "home/base.html" %}

{% load static %}

{% block title %}
    OPTICS-TUTORIALS
{% endblock %}

{% block extra_stylesheet %}

{% endblock %}

{% block content %}
    {% for section in sections %}
        <h2>{{ section.name }}</h2>
        {% for tutorial in tutorials %}
            {% if tutorial.section_id == section.id %}
                <a href="{% url 'contents:unity' %}">
                    <button>
                        <h3>{{ tutorial.name }}</h3>
                        <p>{{ tutorial.description }}</p>
                    </button>
                </a>
            {% endif %}
        {% endfor %}
    {% endfor %}
{% endblock %}

contents/templates/contents/unity.html
{% extends "home/base.html" %}

{% load static %}

{% block title %}
    OPTICS-TUTORIAL
{% endblock %}

{% block extra_stylesheet %}
    <link rel="stylesheet" href="{% static 'contents/unity.css' %}">
{% endblock %}

{% block content %}
    <div id="unity-container">
      <canvas id="unity-canvas"></canvas>
      <div id="unity-loading-bar">
        <div id="optics-logo"></div>
        <div id="unity-progress-bar-empty">
          <div id="unity-progress-bar-full"></div>
        </div>
      </div>
      <div id="unity-warning"> </div>
    </div>
    <script src="{% static 'contents/unity.template.js' %}"></script>
    <script src="{% static 'contents/unity.instance.js' %}"></script>
{% endblock %}

contents/templates/contents/user_scene_list.html
{% extends "home/base.html" %}

{% load static %}

{% block title %}
    OPTICS-SCENES
{% endblock %}

{% block extra_stylesheet %}

{% endblock %}

{% block content %}
        <ul>
            {% for scene in scenes %}
                <li>
                    Name: {{ scene.name }}<br>
                    Description: {{ scene.description }}<br>
                    Last Modify Time: {{ scene.last_modified }}<br>
                </li>
            {% endfor %}
        </ul>
{% endblock %}